services:
  - type: web
    name: clothes-billing-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: billu-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: billu-db
    databaseName: billu
    user: postgres
    plan: free
